// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlQAxxx0VP8oUDigdgmdVmAPnOlJW-PNg',
    appId: '1:155233440869:web:6e5bdf65e6ab33509c228c',
    messagingSenderId: '155233440869',
    projectId: 'chess-test-f33d1',
    authDomain: 'chess-test-f33d1.firebaseapp.com',
    storageBucket: 'chess-test-f33d1.firebasestorage.app',
    measurementId: 'G-HETE5ZRCLZ',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoPApC-hkAyA8oh1yC4lVHeHtJI_4bv5M',
    appId: '1:155233440869:android:9f8d9632cb4f327c9c228c',
    messagingSenderId: '155233440869',
    projectId: 'chess-test-f33d1',
    storageBucket: 'chess-test-f33d1.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1r5wJ9McCcxThpc6BjcpEdj3FnLIWNTQ',
    appId: '1:155233440869:ios:a05e714be4cb1fcb9c228c',
    messagingSenderId: '155233440869',
    projectId: 'chess-test-f33d1',
    storageBucket: 'chess-test-f33d1.firebasestorage.app',
    iosBundleId: 'com.example.chessTest',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlQAxxx0VP8oUDigdgmdVmAPnOlJW-PNg',
    appId: '1:155233440869:web:fa6c101179efc5419c228c',
    messagingSenderId: '155233440869',
    projectId: 'chess-test-f33d1',
    authDomain: 'chess-test-f33d1.firebaseapp.com',
    storageBucket: 'chess-test-f33d1.firebasestorage.app',
    measurementId: 'G-JF5KFY3EDZ',
  );
}
